// Copyright 2011 Google Inc.  All rights reserved.
// Author: borman@google.com (Paul Borman)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package uuid

import (
	"crypto/md5"
	"crypto/sha1"
	"os"
)

// A Hash defines a hashing function.
type Hash interface {
	Reset()
	Write([]byte) (int, os.Error)
	Sum() []byte
}

// Well known Name Space IDs and UUIDs
var (
	NameSpace_DNS  = Decode("6ba7b810-9dad-11d1-80b4-00c04fd430c8")
	NameSpace_URL  = Decode("6ba7b811-9dad-11d1-80b4-00c04fd430c8")
	NameSpace_OID  = Decode("6ba7b812-9dad-11d1-80b4-00c04fd430c8")
	NameSpace_X500 = Decode("6ba7b814-9dad-11d1-80b4-00c04fd430c8")
	NIL            = Decode("00000000-0000-0000-0000-000000000000")
)

// NewHash returns a new UUID dervied from the hash of space concatenated with
// data generated by h.  The hash should be at least 16 byte in length.  The
// first 16 bytes of the hash are used to form the UUID.  The version of the
// UUID will be the lower 4 bits of version.  NewHash is used to implement
// NewMD5 and NewSHA1.
func NewHash(h Hash, space UUID, data []byte, version int) UUID {
	h.Reset()
	h.Write(space)
	h.Write([]byte(data))
	s := h.Sum()
	uuid := make([]byte, 16)
	copy(uuid, s)
	uuid[6] = (uuid[6] & 0x0f) | uint8((version&0xf)<<4)
	uuid[8] = (uuid[8] & 0x3f) | 0x80 // RFC 4122 variant
	return uuid
}

// NewMD5 returns a new MD5 (Version 3) UUID based on the
// supplied name space and data.
//
//  NewHash(md5.New(), space, data, 3)
func NewMD5(space UUID, data []byte) UUID {
	return NewHash(md5.New(), space, data, 3)
}

// NewSHA1 returns a new SHA1 (Version 5) UUID based on the
// supplied name space and data.
//
//  NewHash(sha1.New(), space, data, 5)
func NewSHA1(space UUID, data []byte) UUID {
	return NewHash(sha1.New(), space, data, 5)
}
