# Copyright 2011 Google Inc.  All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include ${GOROOT}/src/Make.inc

TARG=go-uuid.googlecode.com/hg/uuid
GOFILES=\
	hash.go\
	dce.go\
	node.go\
	uuid.go\
	util.go\
	time.go\
	version1.go\
	version4.go\

include ${GOROOT}/src/Make.pkg
