name: Go

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        version: v1.40.1
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -race -v -count=1 -coverprofile=coverage.out ./...
    - name: Upload Code Coverage
      uses: codecov/codecov-action@v1.5.2
      with:
        fail_ci_if_error: true
