---
name: tests
on:
  pull_request:
    branches:
      - master
permissions:
  contents: read
jobs:
  unit-tests:
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x, 1.22]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: ${{ matrix.go-version }}
      - run: go test -v ./...
